name: Publish to npm

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Build package
        run: |
          rm -rf .medusa/server
          yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: medusa-server-release-${{ github.sha }}
          path: .medusa/server
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 14

      - name: Publish package
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}